variable "name_prefix" {
  description = "Prefix applied to all resource names, e.g. 'myapp-dev'."
  type        = string
}

variable "db_subnet_ids" {
  description = "Private database subnet IDs. Minimum two AZs, even for a single-AZ instance."
  type        = list(string)

  validation {
    condition     = length(var.db_subnet_ids) >= 2
    error_message = "RDS requires a subnet group spanning at least two Availability Zones."
  }
}

variable "security_group_id" {
  description = "Security Group for the database. Should permit the application tier only."
  type        = string
}

variable "engine" {
  description = "Database engine."
  type        = string
  default     = "postgres"
}

variable "engine_version" {
  description = "Engine major version. Specify only the major version so AWS selects the latest supported minor release."
  type        = string
  default     = "16"
}

variable "parameter_group_family" {
  description = "Parameter group family. Must match the engine version, e.g. postgres16."
  type        = string
  default     = "postgres16"
}

variable "instance_class" {
  description = "Instance class. A primary cost lever between environments."
  type        = string
  default     = "db.t4g.micro"
}

variable "allocated_storage" {
  description = "Initial storage in GB. Minimum 20 for most engines."
  type        = number
  default     = 20
}

variable "max_allocated_storage" {
  description = "Ceiling for storage autoscaling in GB. Set equal to allocated_storage to disable autoscaling."
  type        = number
  default     = 100
}

variable "storage_type" {
  description = "Storage type. gp3 offers better baseline performance than gp2 at similar cost."
  type        = string
  default     = "gp3"
}

variable "kms_key_id" {
  description = "Customer-managed KMS key ARN for encryption at rest. Null uses the AWS-managed RDS key, which is free."
  type        = string
  default     = null
}

variable "database_name" {
  description = "Name of the initial database created on the instance."
  type        = string
  default     = "appdb"
}

variable "master_username" {
  description = "Master username. The PASSWORD is generated by RDS and stored in Secrets Manager - it is never set here."
  type        = string
  default     = "dbadmin"
}

variable "port" {
  description = "Database port. 5432 for PostgreSQL, 3306 for MySQL."
  type        = number
  default     = 5432
}

variable "multi_az" {
  description = "Run a synchronous standby in a second AZ with automatic failover. DOUBLES the instance cost. Production only."
  type        = bool
  default     = false
}

variable "backup_retention_period" {
  description = "Days to retain automated backups. 0 disables backups and point-in-time recovery entirely - never use 0 in production."
  type        = number
  default     = 7

  validation {
    condition     = var.backup_retention_period >= 0 && var.backup_retention_period <= 35
    error_message = "backup_retention_period must be between 0 and 35 days."
  }
}

variable "backup_window" {
  description = "Daily backup window in UTC, format hh:mm-hh:mm. Choose a low-traffic period."
  type        = string
  default     = "18:00-19:00"
}

variable "maintenance_window" {
  description = "Weekly maintenance window in UTC, format ddd:hh:mm-ddd:hh:mm. Must not overlap the backup window."
  type        = string
  default     = "sun:19:30-sun:20:30"
}

variable "deletion_protection" {
  description = "Prevent deletion of the instance. Must be disabled and applied before a genuine teardown."
  type        = bool
  default     = false
}

variable "skip_final_snapshot" {
  description = "Skip the final snapshot on deletion. True in dev to avoid orphaned snapshots that keep billing; false in production."
  type        = bool
  default     = true
}

variable "final_snapshot_suffix" {
  description = "Suffix making the final snapshot identifier unique. Pass a timestamp or build number - reusing an existing snapshot name causes destroy to fail."
  type        = string
  default     = "snapshot"
}

variable "enabled_cloudwatch_logs_exports" {
  description = "Log types to publish to CloudWatch. For PostgreSQL: postgresql, upgrade."
  type        = list(string)
  default     = ["postgresql"]
}

variable "performance_insights_enabled" {
  description = "Enable Performance Insights. Free at 7-day retention."
  type        = bool
  default     = false
}

variable "performance_insights_retention_period" {
  description = "Performance Insights retention in days. 7 is free; longer is billed."
  type        = number
  default     = 7
}

variable "monitoring_interval" {
  description = "Enhanced Monitoring granularity in seconds (0, 1, 5, 10, 15, 30, 60). 0 disables it. Metrics are billed through CloudWatch Logs."
  type        = number
  default     = 0
}

variable "log_min_duration_statement" {
  description = "Log queries slower than this many milliseconds. -1 disables slow-query logging."
  type        = number
  default     = 1000
}

variable "apply_immediately" {
  description = "Apply modifications immediately instead of during the maintenance window. Many changes cause a reboot, so keep this false in production."
  type        = bool
  default     = false
}

variable "tags" {
  description = "Tags applied to every resource this module creates."
  type        = map(string)
  default     = {}
}
