###############################################################################
# DEV ENVIRONMENT VALUES
#
# This file is the ONLY meaningful difference between dev and production.
# Same modules, same main.tf, same variables.tf - different numbers.
#
# DEV PHILOSOPHY: cheapest configuration that still exercises the real
# architecture. Fast to create, fast to destroy, safe to break.
#
# Contains NO secrets. The database password is generated by RDS and stored
# in Secrets Manager; it never appears here or in Terraform state.
###############################################################################

environment = "dev"
aws_region  = "ap-south-1"
aws_profile = "terraform"

project_name   = "aws-tf-infra"
owner          = "shravani"
cost_center    = "learning"
repository_url = "https://github.com/aryarautt/aws-terraform-multi-env-infra"

# ---- Network ----------------------------------------------------------------
# Each environment gets a DIFFERENT CIDR. If these overlapped, the VPCs
# could never be peered or connected to a shared network later.
#   dev        10.0.0.0/16
#   staging    10.1.0.0/16
#   production 10.2.0.0/16
vpc_cidr = "10.0.0.0/16"
az_count = 2

# BIGGEST COST SAVING IN THIS FILE.
# A NAT Gateway is ~$40/month and is in no free tier. dev runs without one.
# The S3 Gateway Endpoint (free) still gives instances access to S3, and
# SSM Session Manager still works for shell access.
#
# TRADE-OFF: instances cannot reach the public internet, so `dnf update`
# in user data will fail. Acceptable in dev; the architecture is otherwise
# identical.
enable_nat_gateway = false
single_nat_gateway = true

enable_flow_logs = false

# ---- Compute ----------------------------------------------------------------
instance_type        = "t3.micro"
root_volume_size     = 20
asg_min_size         = 1
asg_max_size         = 2
asg_desired_capacity = 1

enable_autoscaling         = false
enable_detailed_monitoring = false

# ---- Load balancer ----------------------------------------------------------
# No certificate: HTTP only.
#
# LEARNING-ONLY SHORTCUT, clearly labelled. Serving a real application over
# plain HTTP is not acceptable in production - credentials and session
# cookies travel in cleartext.
#
# PRODUCTION-SAFE ALTERNATIVE: request a free ACM certificate for a domain
# you own, set certificate_arn, and the module automatically creates an
# HTTPS listener and 301-redirects all HTTP traffic to it. See
# environments/production/terraform.tfvars.
certificate_arn         = null
alb_deletion_protection = false
enable_alb_access_logs  = false

# ---- Database ---------------------------------------------------------------
# Set enable_rds = false to save a further ~$13/month while working on
# networking and compute phases.
enable_rds = true

db_instance_class        = "db.t4g.micro"
db_allocated_storage     = 20
db_max_allocated_storage = 50

# Single AZ. Multi-AZ doubles the cost and dev does not need failover.
db_multi_az = false

# 1 day of backups - enough to prove backups work, minimal storage cost.
db_backup_retention_period = 1

# Both false so `terraform destroy` actually works in dev.
db_deletion_protection = false

# true prevents an orphaned snapshot that keeps billing after teardown.
db_skip_final_snapshot = true

db_performance_insights = false
db_monitoring_interval  = 0

# ---- Storage ----------------------------------------------------------------
# true lets destroy remove a bucket that still has objects in it.
s3_force_destroy           = true
s3_enable_versioning       = true
s3_noncurrent_version_days = 7

# ---- Monitoring -------------------------------------------------------------
log_retention_days  = 7
cpu_alarm_threshold = 85
create_dashboard    = true

# Uncomment and set to receive alarm emails. AWS sends a confirmation link
# that must be clicked before any alarm is delivered.
# alarm_email = "you@example.com"
